plugins {
    id 'java'
    id 'com.github.johnrengelman.shadow' version '8.1.1'
}

group = 'dev.ovis.futureplots.core'
version = '1.0.0'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'

    implementation 'org.mongodb:mongodb-driver-sync:5.2.1'
    implementation 'org.json:json:20231013'
    implementation 'org.redisson:redisson:3.52.0'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

test {
    useJUnitPlatform()
}

shadowJar {
    archiveBaseName.set('futureplots-core')
    archiveClassifier.set('')
    archiveVersion.set('')
}